# This is a basic workflow to help you get started with Actions

name: Main Workflow

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Get main
              run: git fetch origin main
            - name: Install dependencies
              run: npm install
            - name: Install Jest globally
              run: sudo npm install -g jest
            - name: Run Tests
              run: npm run test
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
