# This is the production pipeline to build the artifacts and deploy them to AWS
name: Production Build and Deploy
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Build
            - name: Install NodeJS modules and dependencies
              run: yarn install

            # Build
            - name: Build production artifacts
              run: yarn build

            # Test one last time
            - name: Test app
              run: yarn test

            # Deploy to an AWS S3
            - name: Deploying to AWS S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: 'build'
